import { NextResponse } from "next/server";
import { v2 as cloudinary } from "cloudinary";
import dbConnect from "@/lib/db";
import { Project } from "@/models/Project";

// Configure Cloudinary (Server-side only)
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

export async function POST(req: Request) {
  try {
    // ---------------------------------------------------------
    // 1. AUTHENTICATION & INPUT VALIDATION
    // ---------------------------------------------------------
    const authHeader = req.headers.get("authorization");
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      return NextResponse.json({ error: "Missing Hugging Face API Key in Settings." }, { status: 401 });
    }
    const userHfKey = authHeader.split("Bearer ")[1];

    const body = await req.json();
    const { prompt, projectId, sceneNumber, imageModel } = body;

    if (!prompt || !projectId || sceneNumber === undefined) {
      return NextResponse.json({ error: "Missing required fields (prompt, projectId, sceneNumber)." }, { status: 400 });
    }

    await dbConnect();

    // ---------------------------------------------------------
    // 2. FETCH GLOBAL CONTEXT & ENHANCE PROMPT
    // ---------------------------------------------------------
    const project = await Project.findById(projectId);
    if (!project) {
      return NextResponse.json({ error: "Project not found in database." }, { status: 404 });
    }

    // Extract the global look and feel generated by the Director AI earlier
    const visualMeta = project.visualMetadata || {};
    const globalStyle = visualMeta.style || "highly detailed cinematic masterpiece";
    const globalLighting = visualMeta.lighting || "dramatic studio lighting";
    const globalColors = visualMeta.colors ? `Color grading: ${visualMeta.colors}` : "";

    // Weave the user's action into the global cinematic context
    const enhancedPrompt = `
      ${prompt}. 
      Style: ${globalStyle}. 
      Lighting: ${globalLighting}. 
      ${globalColors}. 
      Shot on ARRI Alexa 65, 35mm lens, 8k resolution, photorealistic, film grain, cinematic depth of field.
    `.replace(/\s+/g, " ").trim();

    console.log(`🎬 Generating Frame for Scene ${sceneNumber}:`, enhancedPrompt);

    // Set production-grade parameters for FLUX.1
    const hfParameters = {
      guidance_scale: 7.5,
      num_inference_steps: 4, // Optimal for FLUX.1-schnell
    };

    // ---------------------------------------------------------
    // 3. GENERATE IMAGE WITH HUGGING FACE (WITH ADVANCED ERROR CATCHING)
    // ---------------------------------------------------------
    const targetModel = imageModel || "black-forest-labs/FLUX.1-schnell";
    
    const hfResponse = await fetch(
      `https://router.huggingface.co/hf-inference/models/${targetModel}`,
      {
        headers: {
          Authorization: `Bearer ${userHfKey}`,
          "Content-Type": "application/json",
        },
        method: "POST",
        body: JSON.stringify({ 
          inputs: enhancedPrompt,
          parameters: hfParameters
        }),
      }
    );

    // --- GRANULAR ERROR PARSING ---
    if (!hfResponse.ok) {
      let errorMessage = "Failed to generate image from AI provider.";
      let statusCode = hfResponse.status;

      try {
        const errorData = await hfResponse.json();
        
        // HF specific error handling
        if (statusCode === 401) errorMessage = "Invalid Hugging Face API Key. Please update it in Settings.";
        else if (statusCode === 429) errorMessage = "Hugging Face rate limit exceeded. Try again in an hour or upgrade your HF account.";
        else if (statusCode === 503 && errorData.estimated_time) {
          errorMessage = `The AI model is currently booting up. Please try again in ${Math.round(errorData.estimated_time)} seconds.`;
        } else if (errorData.error && typeof errorData.error === 'string' && errorData.error.toLowerCase().includes("nsfw")) {
           errorMessage = "Safety Filter Triggered: The prompt generated content that violates Hugging Face safety guidelines. Please adjust the prompt.";
        } else if (errorData.error) {
          errorMessage = `Hugging Face Error: ${errorData.error}`;
        }
      } catch (parseError) {
        // If HF returns plain text instead of JSON
        const rawText = await hfResponse.text();
        console.error("HF Raw Error:", rawText);
      }

      console.error(`🚨 Image Gen Error (Status ${statusCode}):`, errorMessage);
      return NextResponse.json({ error: errorMessage }, { status: statusCode });
    }

    // ---------------------------------------------------------
    // 4. CLOUDINARY UPLOAD PIPELINE
    // ---------------------------------------------------------
    const arrayBuffer = await hfResponse.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    const cloudinaryUrl = await new Promise<string>((resolve, reject) => {
      const uploadStream = cloudinary.uploader.upload_stream(
        { 
          folder: `director_ai/${projectId}/frames`,
          public_id: `scene_${sceneNumber}_frame`,
          overwrite: true // Prevents storage bloat if they regenerate the same scene
        }, 
        (error, result) => {
          if (error) {
            console.error("Cloudinary Upload Error:", error);
            reject(new Error("Failed to save image to cloud storage."));
          } else {
            resolve(result!.secure_url);
          }
        }
      );
      uploadStream.end(buffer);
    });

    // ---------------------------------------------------------
    // 5. DATABASE SYNCHRONIZATION
    // ---------------------------------------------------------
    // Update the Linked Keyframe Architecture fields (frame_url & hf_parameters)
    const updatedProject = await Project.findOneAndUpdate(
      { _id: projectId, "storyboard.scene_number": sceneNumber },
      { 
        $set: { 
          "storyboard.$.frame_url": cloudinaryUrl,
          "storyboard.$.hf_parameters": hfParameters // Save params so the exact style is reproducible
        } 
      }, 
      { new: true }
    );

    if (!updatedProject) {
      console.error(`🚨 Failed to update DB for project ${projectId}, scene ${sceneNumber}`);
      return NextResponse.json({ error: "Image generated, but failed to save to database." }, { status: 500 });
    }

    // 6. Return success to UI
    return NextResponse.json({ 
      status: "success",
      imageUrl: cloudinaryUrl 
    });

  } catch (error: any) {
    console.error("🔥 Fatal Server Error in Generate Image:", error);
    return NextResponse.json({ 
      error: error.message || "An unexpected internal server error occurred." 
    }, { status: 500 });
  }
}